name: weight_tracker
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  cloud_firestore: ^5.6.7
  firebase_auth: ^5.5.3
  firebase_core: ^3.13.0
  flutter:
    sdk: flutter
  freezed_annotation: ^3.0.0
  get: ^4.7.2
  json_annotation: ^4.9.0
  magic_extensions: ^0.0.8
  syncfusion_flutter_charts: ^29.1.40
  syncfusion_flutter_core: ^29.1.40
  url_launcher: ^6.3.1

dev_dependencies:
  build_runner: ^2.4.15
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  freezed: ^3.0.6
  json_serializable: ^6.9.5

flutter:
  uses-material-design: true
